### ISSUE TITLE
Build "fat" library for third party integrations

### ISSUE THREAD

**Issue by ckristhoff** [evertec/athmovil-ios-sdk#1]
Hi,
I'm Xamarin developer. I'm trying to integrate ATH Móvil as payment method but I'm having some troubles. Where to configure cocoapods workspace? Why Xcode raises deprecated swift version error?

**Comment by hinsona** [comment]
Our app uses Xamarin forms, and I am now looking at the possibility of using the ATH Movil native platform APIs. Were you able to get this working with Xamarin?

**Comment by ckristhoff** [comment]
Hi @hinsona , I lose much time trying to integrate ATH movil with Xamarin. Ath movil lib team does not help for nothing.
My recommendation, change you framework. I already integrate ATH Movil in react native project an it works really well in both android  and ios.

**Comment by hinsona** [comment]
> Hi @hinsona , I lose much time trying to integrate ATH movil with Xamarin. Ath movil lib team does not help for nothing.
> My recommendation, change you framework. I already integrate ATH Movil in react native project an it works really well in both android and ios.

>Ath movil lib team does not help for nothing.

Thank you for replying. I've noticed this as well. They seem to be using github to publish their API more so than anything else.

Adding ATH Movil support for me is a feature requested for an existing mobile project. To switch frameworks at this point is highly improbable.

**Comment by leovazquezz1** [comment]
Hi @ckristhoff I am looking to integrate ATH Movil to a react native app and I am having a hard time doing so. How did you do it? I am currently in the process bridging react native with swift for using native athmovil-ios-sdk.

**Comment by ckristhoff** [comment]
Hi @leovazquezz1 
It's very easy if you know swift or objective-c, just follow the [RN documentation](https://reactnative.dev/docs/native-modules-ios)
I can tell you the athmovil-ios-sdk has some issues. The simulator does not works how you spects, to solve you need change some code. Contact me if you need more help.

**Comment by hinsona** [comment]
We ended up implementing the JS API in Xamarin using the browser control. It's not native, but it works in both iOS and Android. 🤷‍♂️

**Comment by leovazquezz1** [comment]
@hinsona how did you work the js api? The problem we have when we implement it with the browser of the device is that the Ath Movil integration opens a new window and the browser does not recognize the new window open. Also customers have to login every time they want to pay via the browser, this is also painful.

@ckristhoff do you know how can we implement using the native modules in react native? I worked something with Ath Movil integration natively but I cannot test it with the simulator or make it work on production. Do you know someone that have done this type of integration in react native? I still have to spent time figuring out the Ath Movil implementation.

**Comment by ckristhoff** [comment]
@leovazquezz1 pm @ckristhoff at facebook.

**Comment by Cyberfolks** [comment]
@ckristhoff  can you please share your code (react native integration with ios and android) to help us. As i know the time is very important but it will help us to manage many things. Thanks in advance.

**Comment by hinsona** [comment]
> @hinsona how did you work the js api? The problem we have when we implement it with the browser of the device is that the Ath Movil integration opens a new window and the browser does not recognize the new window open. Also customers have to login every time they want to pay via the browser, this is also painful.

This example is how we accomplished using ATH Movil JS API using Xamarin forms.

Using the WebView control. This keeps  the user within your application for as long as possible but it does add one middle step that might be possible to eliminate if using JS directly.

1. In our app we have a button on our payment page to use ATH Movil. If the user taps this button it redirects the user to a WebView with payment summary and another button to continue to ATH Movil.
2. From the summary page we show information about the payment to the user and save the json data to our database to be used later for verify payment is complete. Since the page also hosts the ATH Movil JS API control it renders the Pay with ATH button - there's not a lot you can control with the button since the API handles it. Payment info from our app is forwarded here using a URL parameter that is a base64 encoded json object. The object is then handled by the page and forwarded to ATH Movil when the user taps the API button. When proceeding it triggers the JS onclick handler of the ATH Movil API, which prompts the user to login with ATH Movil. Once logged in the user will receive a notification from the ATH Movil app that payment has been requested and to authorize the payment. If the user follows the toast notification it will take them directly to the payment in the ATH Movil app. If they open the app manually they'll be prompted when it opens to authorize the recent payment or they can find it manually. They can also use the website to do this as well - not sure why they would but it does work even it opened on another device.
3. On our web server, we have a cron/scheduled job to poll the ATH webservice (noted in their API docs) to ensure that payment was completed by the user. Here you search for the guid you created earlier in step two as the key for your payment. We just pull back payments within the day and check if the result contains our guid. This updates our local database to reflect that payment is completed. This allows the payment verification process to be asynchronous from the app itself.
4. When the user returns to our app if it's on the ATH Movil payment page we check that the payment is complete. If it is completed we allow them to continue and to finalize things.

Hope that helps.

**Comment by hinsona** [comment]
> @hinsona how did you work the js api? The problem we have when we implement it with the browser of the device is that the Ath Movil integration opens a new window and the browser does not recognize the new window open. Also customers have to login every time they want to pay via the browser, this is also painful.

This example is how we accomplished using ATH Movil JS API using Xamarin forms.

Using the WebView control. This keeps  the user within your application for as long as possible but it does add one middle step that might be possible to eliminate if using JS directly.

1. In our app we have a button on our payment page to use ATH Movil. If the user taps this button it redirects the user to a WebView with payment summary and another button to continue to ATH Movil.
2. From the summary page we show information about the payment to the user and save the json data to our database to be used later when verifying that the payment is complete. Since the page also hosts the ATH Movil JS API control it renders the Pay with ATH button - there's not a lot you can control with the button since the API handles it. Payment info from our app is forwarded here using a URL parameter that is a base64 encoded json object. The object is then handled by the page and forwarded to ATH Movil when the user taps the API button. When proceeding it triggers the JS onclick handler of the ATH Movil API, which prompts the user to login with ATH Movil. Once logged in the user will receive a notification from the ATH Movil app that payment has been requested and to authorize the payment. If the user follows the toast notification it will take them directly to the payment in the ATH Movil app. If they open the app manually they'll be prompted when it opens to authorize the recent payment or they can find it manually. They can also use the website to do this as well - not sure why they would but it does work even it opened on another device.
3. On our web server, we have a cron/scheduled job to poll the ATH webservice (noted in their API docs) to ensure that payment was completed by the user. Here you search for the guid you created earlier in step two as the key for your payment. We just pull back payments within the day and check if the result contains our guid. This updates our local database to reflect that payment is completed. This allows the payment verification process to be asynchronous from our app.
4. When the user returns to our app if it's on the ATH Movil payment page we check that the payment is complete by checking our local database. If it was completed by our cron job we allow them to continue to finalize things.

I hope this helps. 

Evertec should invest in officially supporting Xamarin. We were able to speak with Evertec's technical folks about the issues we encountered with the API. We offered to work with them to create official Xamarin support, etc. They didn't seem interested.

**Comment by hansy-dev** [comment]
Hello

I close this issue because version 3.0 has a script named _Xamarin.sh_ this script allows you to create the library and the class for Xamarin project. You can find more information in the [XamarinReadME](https://github.com/evertec/athmovil-ios-sdk/blob/master/READMEXamarin.md).

Regards

**Comment by hinsona** [comment]
Will there be something similar for Xamarin.Android?

**Comment by hansy-dev** [comment]
No, There is not script for Xamarin.Android. You can follow the next [link](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/). The Android Team tested the current SDK version with that link so if you have any questions please you can comment in the Android SDK.
